name: Update develop

on:
  pull_request:
    branches:
      - develop
    types:
      - closed
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && (startsWith(github.event.pull_request.head.ref, 'feature/'))
    strategy:
      matrix:
        java: [ 11 ]
    name: Build project with Java ${{ matrix.java }}

    env:
      DEVOPS_CICD_ECR_BASE_URL: ${{ secrets.DEVOPS_CICD_ECR_BASE_URL }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      BB_USERNAME: ${{ secrets.BAAS_BB_ARTIFACTORY_MAVEN_USERNAME }}
      BB_PASSWORD: ${{ secrets.BAAS_BB_ARTIFACTORY_MAVEN_PASSWORD }}
      BB_GITHUB_PACKAGES_USER: ${{ secrets.BB_GITHUB_PACKAGES_USER }}
      BB_GITHUB_PACKAGES_PAT: ${{ secrets.BB_GITHUB_PACKAGES_PAT }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Cache Maven Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
            ${{ runner.os }}-

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Maven setup with credentials
        uses: whelk-io/maven-settings-xml-action@v9
        with:
          repositories: |
            [
              {"id": "github-packages", "url": "https://maven.pkg.github.com/baas-devops-cnb/*"},
              {"id": "Backbase Repository", "url": "https://repo.backbase.com/repo"}
            ]
          plugin_repositories: |
            [
              {"id": "Backbase Repository", "url": "https://repo.backbase.com/repo"}
            ]
          servers: |
            [
              {"id": "Backbase Repository", "username": "${{ secrets.BAAS_BB_ARTIFACTORY_MAVEN_USERNAME }}", "password": "${{ secrets.BAAS_BB_ARTIFACTORY_MAVEN_PASSWORD }}"},
              {"id": "github-packages", "username": "${BB_GITHUB_PACKAGES_USER}", "password": "${{ secrets.BB_GITHUB_PACKAGES_PAT }}"}
            ]

      - name: Run Blackduck scan
        uses: blackducksoftware/github-action@v2.2
        with:
          blackduck.url: "${{ secrets.BLACKDUCK_API_URL }}"
          blackduck.api.token: "${{ secrets.CNBB_BLACKDUCK_API_TOKEN }}"
          args:
           --detect.project.name="CS-CNBB-Backend"
           --detect.project.version.name="latest"
           --detect.code.location.name="${{ github.event.repository.name }}"
           --detect.tools=DETECTOR
           --detect.source.path="./"
           --detect.included.detector.types=MAVEN
           --detect.maven.excluded.scopes=test

      - name: Bump snapshot version
        run: |
          mvn build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion}-SNAPSHOT versions:commit
          git config --global user.email "bot@backbase.com"
          git config --global user.name "Release BOT"
          git add --all
          git commit -m "Bumping SNAPSHOT Version"
          git push

      - name: Publish to GitHub Packages
        run: mvn -B deploy -DaltDeploymentRepository=github-packages::default::https://maven.pkg.github.com/baas-devops-cnb/${{ github.event.repository.name }}
